= About Starlight for JMS
:navtitle: Starlight for JMS

{jms_repo}[Starlight for JMS] is the first highly compliant JMS implementation designed to run on a modern streaming platform.
It allows enterprises to take advantage of the scalability and resiliency of a modern streaming platform to run their existing JMS applications. Because Apache Pulsar(TM) is open-source and cloud-native, Starlight for JMS enables enterprises to move their JMS applications to run on-premises and in any cloud environment.

== Key Features

Starlight for JMS key features include:

* *Blazing fast JMS performance*: Achieve 1 million JMS messages per second with 99 percentile publish to acknowledge latency of less than 10 ms.
* *Drop-in replacement for existing JMS applications*: Supports JMS/Jakarta 2.0 and is backwards compatible with JMS 1.1. 100% pass rate on JMS compliance test for supported features.
* *Horizontally scalable JMS*: Apache Pulsar is a horizontally scaled distributed streaming platform. You can scale up or down without operational hassles. Pulsar separates compute from storage, which means you can scale those dimensions independently, as required. Pulsar supports offloading old data to object storage for practically infinite storage capacity.
* *Reduced total cost of ownership*: Because Apache Pulsar is natively multi-tenant and high performance, you can consolidate JMS applications spread across multiple legacy JMS brokers onto a single Apache Pulsar installation. And since Pulsar is easily horizontally scaled, you don't need to overprovision.
* *Future proof*: Apache Pulsar can support traditional messaging workloads, but it can also support modern streaming use cases such as log collection, microservices integration, event streaming, event sourcing. New workloads can run alongside Legacy JMS applications.
* *Open source to avoid lock in*: Starlight for JMS and Apache Pulsar are 100% open source. You can run on-premise, in any cloud provider, or in Kubernetes.
* *Adds message replay to JMS*: Apache Pulsar natively supports message retention and replay. This allows applications using Fast JMS for Apache Pulsar to travel back in time and replay previously consumed messages to recover from misconfiguration issues, recover from bugs in application code, and test new applications against real data.

== Get started with Starlight for JMS

* xref:jms-migration:pulsar-jms-quickstart-sa.adoc[]
* xref:jms-migration:pulsar-jms-install.adoc[]
* xref:ROOT:pulsar-jms-faq.adoc[]

== Learn more about Starlight for JMS

* xref:reference:pulsar-jms-mappings.adoc[]
* xref:examples:pulsar-jms-implementation.adoc[]
* xref:reference:pulsar-jms-reference.adoc[]
