= Starlight for JMS FAQs
:navtitle: FAQs

Answers to common Starlight for JMS questions.

== What is the pricing for Starlight for JMS?

Starlight for JMS is open source and is included in https://www.ibm.com/docs/en/supportforpulsar[IBM Elite Support for Apache Pulsar].

== How is Starlight for JMS licensed?

Starlight for JMS is licensed under https://www.apache.org/licenses/LICENSE-2.0.txt[Apache version 2.0].

== How can I use Starlight for JMS in a JakartaEE(R) or JavaEE(R) application?

You can use the `resourceAdapter` {jms_repo}blob/master/resource-adapter[here].

== How can I run the Test Compatibility Kit (TCK)

You can download the TCK https://jakarta.ee/specifications/messaging/2.0/[here]. The repository contains a copy of the TCK that automates the execution of the tests.

In the tck-executor module you'll find:

* The Java Code needed to initialize the TCK, `JNDIInitialContextFactory.java`.
* The configuration file for the TCK runner, `ts.jte`.
* A file that contains the excluded tests that cannot pass with this client, `ts.jtx`
* Scripts to run Apache Pulsar 2.7.1, configure the Transaction Coordinator, and prepare for the execution of the TCK.

To build the package, run unit tests, and run the TCK:

[source,bash]
----
mvn clean install -Prun-tck
----

To run only the TCK:

[source,bash]
----
mvn clean install -Prun-tck -am -DskipTests -pl tck-executor
----

IMPORTANT: Globally unique subscription names are not supported so the corresponding tests are skipped.

== Where can I find additional integration examples?

We've provided the following integration examples:

* {jms_repo}blob/master/examples/spring[Spring Boot(R)]
* {jms_repo}blob/master/examples/payara-micro[Payara Micro(R)]
* {jms_repo}blob/master/resource-adapter-tests[Apache TomEE(R)]

== How can I build Starlight for JMS from source?

If you'd like to fork or contribute to Starlight for JMS:

. Clone the git repo:
+
[source,bash]
----
git clone git@github.com:datastax/pulsar-jms.git
----

. Build using Maven:
+
[source,bash]
----
mvn clean install
----

== Where can I find additional information on JMS?

Refer to the https://jakarta.ee/specifications/messaging/2.0/[official JMS documentation] in order to learn about JMS.
This https://javaee.github.io/jms-spec/[website] is useful as well as it contains the former JMS 2.0 specifications before the Jakarta transition.
