= {starlight_jms} FAQs 

:page-tag: starlight-jms,planner,dev,admin,pulsar,jms

Answers to the (arguably) most common {starlight_jms} questions.

== What is the pricing for {starlight_jms}?

{starlight_jms} is free open-source software. Enterprise support is available through https://www.datastax.com/products/luna-streaming[Luna Streaming,window=_blank], the DataStax commercial support offering for Apache Pulsar™.

== How is {starlight_jms} licensed?

{starlight_jms} is licensed under https://www.apache.org/licenses/LICENSE-2.0.txt[Apache version 2.0,window=_blank].

== How can I use {starlight_jms} in a JakartaEE® or JavaEE® application?

You can use the `resourceAdapter` {jms_repo}blob/master/resource-adapter[here,window=_blank].

== How can I run the Test Compatibility Kit (TCK)

You can download the TCK https://jakarta.ee/specifications/messaging/2.0/[here,window=_blank]. The repository contains a copy of the TCK that automates the execution of the tests.

In the tck-executor module you'll find:

* The Java Code needed to initialize the TCK, `JNDIInitialContextFactory.java`.
* The configuration file for the TCK runner, `ts.jte`.
* A file that contains the excluded tests that cannot pass with this client, `ts.jtx`
* Scripts to run Apache Pulsar 2.7.1, configure the Transaction Coordinator, and prepare for the execution of the TCK.

To build the package, run unit tests, and run the TCK:

[source,language-bash]
----
mvn clean install -Prun-tck
----

To run only the TCK:

[source,language-bash]
----
mvn clean install -Prun-tck -am -DskipTests -pl tck-executor
----

IMPORTANT: Globally unique subscription names are not supported so the corresponding tests are skipped.

== Where can I find additional integration examples?

We've provided the following integration examples:

* {jms_repo}blob/master/examples/spring[Spring Boot®,window=_blank]
* {jms_repo}blob/master/examples/payara-micro[Payara Micro®,window=_blank]
* {jms_repo}blob/master/resource-adapter-tests[Apache TomEE®,window=_blank]

== How can I build {starlight_jms} from source?

If you'd like to fork or contribute to {starlight_jms}:

. Clone the git repo:
+
[source,language-bash]
----
git clone git@github.com:datastax/pulsar-jms.git
----

. Build using Maven:
+
[source,language-bash]
----
mvn clean install
----

== Where can I find additional information on JMS?

Refer to the https://jakarta.ee/specifications/messaging/2.0/[official JMS documentation,window=_blank] in order to learn about JMS.
This https://javaee.github.io/jms-spec/[website,window=_blank] is useful as well as it contains the former JMS 2.0 specifications before the Jakarta transition.

== What's next?

* *xref:jms-migration:pulsar-jms-quickstart-sa.adoc[]*: Create a simple command line Java JMS client that connects to a local Pulsar installation.
* *xref:jms-migration:pulsar-jms-quickstart-astra.adoc[]*: Create a simple command line Java JMS client that connects to an Astra Streaming instance.
* *xref:jms-migration:pulsar-jms-install.adoc[]*: Install {starlight_jms} in your own JMS project.
* *xref:reference:pulsar-jms-mappings.adoc[]*: Understand Pulsar concepts in the context of JMS.
* *xref:examples:pulsar-jms-implementation.adoc[]*: Understand key implementation details for {starlight_jms}.
* *xref:reference:pulsar-jms-reference.adoc[]*: {starlight_jms} configuration reference.
* *{jms_repo}[{starlight_jms} Github repo,window=_blank]*
