= Use server-side filters with {product}
:navtitle: Use server-side filters

{product} offers server-side filtering, which executes JMS filtering features on the {pulsar-short} Broker instead of the Client.

Previously, filtering was implemented with `jms.enableClientSideEmulation=true` on the Client side, which meant the Client application received all messages, even if they didn't match the filter. This caused inefficient network, CPU, and memory usage.

Server-side filtering offloads the filtering to the Broker nodes and includes the following JMS filtering features:

* *Broker-side message selectors*: The Broker filters messages instead of the client.
* *Per-message `timeToLive`*: Each message can have a time to live value.
* *`noLocal` filter*: Filter out messages sent from the same connection.

== Limitations

* **Required version**: Server-side filtering requires {pulsar-short} version 2.10.1 or later, or {luna-streaming} (formerly DataStax Luna Streaming) version 2.10 or later.

* *Batch messages*: Server-side filtering works on the entry level in {pulsar-short}.
An _entry_ is a single message, or a single batch of messages.
The Broker cannot selectively filter messages in a batch; it either passes completely or fails completely.
+
For example, if a batch message is partially accepted by the Broker filter, the Broker still sends the entire batch to the client, and the client executes the filter locally.
If you don't want the client to receive unwanted messages, disable batching on your producers.
For more information, see xref:pulsar-jms-batch-ack.adoc[Batch index acknowledgement].
+
[TIP]
====
{pulsar-short} IO Sources enable batching and compression by default.
====

* *Increased Broker resources usage*: The {pulsar-short} Broker doesn't perform processing on messages by default.
When server-side filtering is enabled, the Broker requires additional CPU and heap memory to process filters.
+
{company} recommends disabling compression and batching for messages that will be filtered on the Broker.
Batch messages with compression consume a non-negligible amount of CPU, heap, and direct memory, because filtering requires decompressing the batch to access Message Properties
+
This doesn't apply to compressed single messages.

* *Unsupported message types*: {product} doesn't support encrypted batch messages because the filter can't decode the payload of the entry.
For the same reason, {product} doesn't support custom formats like native {kafka-reg} messages.

== Enable server-side filtering

The `.nar` file filter is packaged with {luna-streaming} version 2.10.03 and later.
It is also available in the {jms_repo}/releases[{product} GitHub repository].

. Install {product} with the fat JAR that includes all dependencies.
Put the `.nar` file in `/pulsar/filters`.
+
The path for the .nar is relative to your {pulsar-short} directory.
+
For more information, see xref:jms-migration:pulsar-jms-quickstart-sa.adoc[quickstart].

. Modify `PulsarConnectionFactory` in {product} to disable client-side emulation and use server-side filtering:
+
[source,plaintext]
----
jms.enableClientSideEmulation=false;
jms.useServerSideFiltering=true;
----

. Modify `broker.conf` to accept `entryFilterNames` and to look for the `.nar` file in `/pulsar/filters`:

[source,plaintext]
----
entryFilterNames=jms
entryFiltersDirectory=/pulsar/filters
----

You're ready to use server-side filtering.

[#selectors]
== Configure per-subscription message selectors on the Broker

{product} allows you to pre-configure the `selector` property when creating your {pulsar-short} subscription.
Modify `PulsarConnectionFactory` in {product} to include the following:

[source,plaintext]
----
jms.filtering=true
jms.selector=YOUR MESSAGE SELECTOR
----

If you have deployed the `.nar` file and configured the `entryFilterNames` and `entryFiltersDirectory` properties in `broker.conf`, then the Broker begins filtering messages automatically.

This only partially works for a non-JMS client because batch messages cannot be completely filtered out by the Broker.
If you use this feature, use a {product} 2.x client and the `jms.useServerSideFiltering` feature.

In this case, the server-side filter applies both to JMS queues and JMS topics.
The JMS client automatically downloads the `jms.selector` from the subscription and applies it locally, where batch message filtering may have partially accepted the message on the Broker.

If you set `jms.selector` on the subscription _and_ set a message selector on the JMS client, then the conditions on the subscription and the JMS client are both fulfilled.

== See also

* xref:reference:pulsar-jms-mappings.adoc[]
* xref:pulsar-jms-implementation.adoc[]
* xref:reference:pulsar-jms-reference.adoc[]