= Use batch index acknowledgement with {product}
:navtitle: Use batch index acknowledgement

{product} improves acknowledgement of batched messages by supporting the tracking of 'ack' status by batch index.

By default, filtering works on the entry level in {pulsar-short}.
An _entry_ is a single message, or a single batch of messages.
The client cannot selectively filter messages in a batch; it either passes completely or fails completely.

With batch index acknowledgement, when the broker dispatches messages, it carries the batch index that has been acknowledged.
Then, the client filters out batch indexes that have been acknowledged.
Finally, the client sends the batch index acknowledgement information to the broker so the broker can maintain the batch index acknowledgement status.

[TIP]
====
{company} strongly recommends using batch index acknowledgement for increased efficiency, whether using broker-side or client-side selectors.
====

== Enable batch index acknowledgement

Batch index acknowledgement requires cooperation between the client and broker.
You must modify both `broker.conf` and the `consumerConfig` JMS client property to enable batch acknowledgement:

. In your `broker.conf` file, add the configuration property `acknowledgmentAtBatchIndexLevelEnabled` and set it to `true`:
+
[source,conf]
----
acknowledgmentAtBatchIndexLevelEnabled=true
----

. In your Java project, set the `consumerConfig` property on the JMS client by adding `consumerConfig.put("batchIndexAckEnabled", true);` to `consumerConfig` in the `ConnectionFactory` configuration:
+
[source,java]
----
    Map<String, Object> properties = new HashMap<>();
    properties.put("webServiceUrl", cluster.getAddress());
    Map<String, Object> consumerConfig = new HashMap<>();
    consumerConfig.put("batchIndexAckEnabled", true);
    properties.put("consumerConfig", consumerConfig);
    try (PulsarConnectionFactory factory = new PulsarConnectionFactory(properties));
----

== See also

* xref:pulsar-jms-server-side-filters.adoc[]
* xref:reference:pulsar-jms-mappings.adoc#consumer-mappings[Consumer mappings]