= Install Starlight for JMS
:navtitle: Installation

Install {jms_repo}[Starlight for JMS] by adding the dependency to your Java project.
For example:

.pom.xml
[source,xml,subs="+quotes"]
----
<dependency>
   <groupId>com.datastax.oss</groupId>
   <artifactId>pulsar-jms-all</artifactId>
   <version>**VERSION**</version>
</dependency>
----

There are two Starlight for JMS packages available:

* **`pulsar-jms`**: This package contains only Starlight for JMS code.
It transitively imports the Pulsar client and the Jakarta JMS 2.0 specifications JAR.
* **`pulsar-jms-all`**: This is the fat JAR that includes Starlight for JMS and all required dependencies, including the Pulsar client and the Jakarta JMS 2.0 specifications.

{company} recommends the latest version whenever possible.
However, certain features and compatibility issues that require a specific version.

[tabs]
======
Astra Streaming::
+
--
The Pulsar version is managed by Astra.
Typically, the latest Starlight for JMS version is compatible with the Pulsar version used by Astra Streaming.
--

Luna Streaming::
+
--
* To use Transactions with Luna Streaming 2.8.x, you must use Starlight for JMS version 1.x.
* To use Transactions with Luna Streaming 2.10.x or later, you must use Starlight for JMS version 2.x or later.
* To use server-side filtering with Luna Streaming, you must use Luna Streaming 2.10.1 or later and Starlight for JMS 2.x or later.
--

Self-managed::
+
--
* To use Transactions with self-managed Pulsar 2.8.x, you must use Starlight for JMS version 1.x.
* To use Transactions with self-managed Pulsar 2.9.x, 2.10.x, or later, you must use Starlight for JMS version 2.x or later.
* To use server-side filtering with self-managed Pulsar, you must use Pulsar 2.10.1 or later and Starlight for JMS 2.x or later.
--
======