= {product} quickstart
:navtitle: Quickstart
:description: Use the {product} API to produce and consume messages on {pulsar-short} topics.

The {jms_repo}[{product}] extension is a highly compliant JMS implementation designed to run on a modern streaming platform.

This guide explains how to prepare an {pulsar-reg} streaming instance, and then use {product} to produce and consume messages with a Java JMS client.

[#prepare-your-pulsar-cluster]
== Prepare your {pulsar-short} cluster

[tabs]
======
{astra-streaming}::
+
--
To use {product} with an {astra-streaming} {pulsar-short} cluster, you need the following:

* An active {astra-streaming} {pulsar-short} cluster with a tenant, namespace, and topic that you want to use with {product}.
If you don't have these structures configured in {astra-streaming}, see the xref:astra-streaming:getting-started:index.adoc[].

* The connection details for your tenant, which are found on the tenant's **Connect** tab under **Tenant Details**:
+
** **Name**: The tenant name
** **Broker Service URL**: The cluster's broker service URL in the format `pulsar+ssl://**CLUSTER**.streaming.datastax.com:6651`
** **Web Service URL**: The cluster's web service URL in the format `https://**CLUSTER**.streaming.datastax.com`
** **Token**: A {pulsar-short} token that provides access to the tenant
--

{luna-streaming}::
+
--
To use {product} with a {luna-streaming} {pulsar-short} cluster, you need the following:

* A {luna-streaming} {pulsar-short} cluster.
+
If you don't have a {luna-streaming} cluster, see the xref:luna-streaming:install-upgrade:quickstart-helm-installs.adoc[{luna-streaming} installation guide].

* Access to the cluster's admin port 8080 and the binary port 6650.
+
[IMPORTANT]
====
You must modify the initialization properties in the quickstart code if your cluster's {pulsar-short} endpoints aren't accessible on `\http://localhost:8080` and `\http://localhost:6650`.
Alternatively, enable port forwarding with `kubectl` to make the endpoints accessible on these URLs.
For more information, see xref:luna-streaming:install-upgrade:quickstart-helm-installs.adoc#install-luna-streaming-locally[Install {luna-streaming} locally].
====
--

Self-managed::
+
--
To use {product} with a self-managed {pulsar-short} cluster, you need a {pulsar-short} cluster with access to the {pulsar-short} admin port 8080 and binary port 6650.

This quickstart uses a local {pulsar-short} Docker instance.
You can also use a local https://pulsar.apache.org/ja/download/[{pulsar} binary] installation or a remote {pulsar-short} cluster.

[IMPORTANT]
====
You must modify the initialization properties in the quickstart code if your cluster's {pulsar-short} endpoints aren't accessible on `\http://localhost:8080` and `\http://localhost:6650`.
Alternatively, enable port forwarding with `kubectl` to make the endpoints accessible on these URLs.
====

To follow along with this quickstart as written, install a {pulsar-short} instance using Docker:

. Install https://docs.docker.com/get-docker/[Docker] on your local machine.

. Open a terminal, and then create a {pulsar-short} Docker instance with ports 8080 and 6650 exposed:
+
[source,bash]
----
docker run --name pulsar-jms-runner -p 8080:8080 -p 6650:6650 apachepulsar/pulsar:latest /pulsar/bin/pulsar standalone
----
+
.Result
[%collapsible]
====
Starting the Docker container produces many status messages and output similar to the following:
[source,bash]
----
14:57:50.996 [pulsar-web-68-11] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/May/2021:14:57:50 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 1677 "-" "Pulsar-Java-v2.7.1" 3
14:58:20.962 [pulsar-web-68-1] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/May/2021:14:58:20 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 1677 "-" "Pulsar-Java-v2.7.1" 3
14:58:50.926 [pulsar-web-68-12] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/May/2021:14:58:50 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 1677 "-" "Pulsar-Java-v2.7.1" 3
14:59:20.892 [pulsar-web-68-2] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/May/2021:14:59:20 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 1677 "-" "Pulsar-Java-v2.7.1" 4
14:59:50.857 [pulsar-web-68-3] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/May/2021:14:59:50 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 1677 "-" "Pulsar-Java-v2.7.1" 3
----
====

. Leave this terminal running in the background while you complete the rest of this quickstart.
--
======

== Produce and consume messages with {product}

This example shows how to produce and consume messages with Starlight for JMS using a JMS client, https://openjdk.java.net/install/[Java OpenJDK] 8 or 11, and https://maven.apache.org/install.html[Apache Maven].
You can also use Gradle with some modifications.

For the complete source code for this example, see the https://github.com/datastax/astra-streaming-examples/tree/master/java/starlight-for-jms[{company} streaming examples repository].
This example was written for {astra-streaming} but it can be used with {luna-streaming} or self-managed {pulsar-short} clusters by setting the connection properties appropriately.

[tabs]
======
{astra-streaming}::
+
--
include::ROOT:partial$jms-quickstart-create-project.adoc[]

. In the `example` directory, create an `App.java` file.
In the next steps, you will add code to this file to create a complete program that produces and consumes messages.

. Paste the following code in the file, and then replace the placeholders with the <<prepare-your-pulsar-cluster,tenant connection details, namespace, and topic from {astra-streaming}>>.
Your editor will report errors because this isn't a complete program yet.
+
./src/main/java/org/example/App.java
[source,java,subs="+quotes"]
----
package org.example;

import com.datastax.oss.pulsar.jms.PulsarConnectionFactory;

import javax.jms.JMSContext;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.Queue;
import java.util.HashMap;
import java.util.Map;

public class App
{
  private static String webServiceUrl = "**WEB_SERVICE_URL**";
  private static String brokerServiceUrl = "**BROKER_SERVICE_URL**";
  private static String pulsarToken = "**TOKEN**";
  private static String tenantName = "**TENANT_NAME**";
  private static final String namespace = "**NAMESPACE_NAME**";
  private static final String topicName = "**TOPIC_NAME**";
  private static final String topic = String.format("persistent://%s/%s/%s", tenantName,namespace,topicName);
  public static void main( String[] args ) throws Exception
  {
----

. Add the following code to build the configuration for the producer and consumer:
+
./src/main/java/org/example/App.java
[source,java]
----
    Map<String, Object> properties = new HashMap<>();
    properties.put("webServiceUrl",webServiceUrl);
    properties.put("brokerServiceUrl",brokerServiceUrl);
    properties.put("authPlugin","org.apache.pulsar.client.impl.auth.AuthenticationToken");
    properties.put("authParams",pulsarToken);
----

. Add the following code to define a simple `PulsarConnectionFactory` that creates a JMS queue using the full {pulsar-short} topic address, creates a message listener callback function that watches the queue, and then produces a single message on the queue:
+
./src/main/java/org/example/App.java
[source,java]
----
    try (PulsarConnectionFactory factory = new PulsarConnectionFactory(properties); ){
      JMSContext context = factory.createContext();
      Queue queue = context.createQueue(topic);

      context.createConsumer(queue).setMessageListener(new MessageListener() {
        @Override
        public void onMessage(Message message) {
          try {
            System.out.println("Received: " + message.getBody(String.class));
          } catch (Exception err) {
            err.printStackTrace();
          }
        }
      });

      String message = "Hello there!";
      System.out.println("Sending: "+message);
      context.createProducer().send(queue, message);

      Thread.sleep(4000); //wait for the message to be consumed
    }
  }
}
----

. Save `App.java`, and then build and run the JAR file for the complete program:
+
[source,bash]
----
mvn clean package assembly:single
java -jar target/StarlightForJMSClient-1.0-SNAPSHOT-jar-with-dependencies.jar
----

. Make sure the result shows that a message was sent and received:
+
[source,console]
----
Sending: Hello there!
Received: Hello there!
----

. In {astra-streaming}, go to your tenant's **Namespaces and Topics** tab to inspect the activity in the namespace that you used in the Java program.
+
If you everything was configured correctly, then the namespace's metrics should reflect that at least one message was published and consumed by your {astra-streaming} {pulsar-short} topic.
--

{luna-streaming}::
+
--
include::ROOT:partial$jms-quickstart-create-project.adoc[]

. In the `example` directory, create an `App.java` file, and then paste the following code into the file:
+
./src/main/java/org/example/App.java
[source,java]
----
package example;

import com.datastax.oss.pulsar.jms.PulsarConnectionFactory;
import javax.jms.JMSContext;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.Queue;
import java.util.HashMap;
import java.util.Map;

public class App {
  public static void main(String ... args) throws Exception {

    String topic = "persistent://public/default/example-topic";

    Map<String, Object> properties = new HashMap<>();

    try (PulsarConnectionFactory factory = new PulsarConnectionFactory(properties); ){
      JMSContext context = factory.createContext();
      Queue queue = context.createQueue(topic);

      // Listen for messages...
      context.createConsumer(queue).setMessageListener(new MessageListener() {
        @Override
        public void onMessage(Message message) {
          try {
              System.out.println("Received: " + message.getBody(String.class));
            } catch (Exception err) {
              err.printStackTrace();
            }
          }
      });

      for (int i = 0; i < 10; i++) {
        String message = "Hello world! " + i;
        System.out.println("Sending: "+message);
        context.createProducer().send(queue, message);
      }

      Thread.sleep(10000);
    }
  }
}
----
+
Note the following elements of the `App.java` program:
+
* **`persistent://public/default/example-topic`**: The topic URI that the client uses to publish and consume messages.
This quickstart uses the default tenant and namespace with a topic named `example-topic`.
The tenant and namespace must already exist.
If the specified topic doesn't exist in the namespace, {product} creates the topic automatically.
* **`Map<String, Object> properties = new HashMap<>();`**: Creates an empty xref:reference:pulsar-jms-reference.adoc[{product} configuration properties] hashmap.
You must override `webServiceUrl` if your {pulsar-short} cluster's admin endpoint isn't accessible on `\http://localhost:8080`.
For remote clusters, additional properties are required, such as the Broker Service URL and authentication credentials.
* **`Queue queue = context.createQueue(topic);`**: Creates a {product} queue.
For more information about queues and topics, see xref:reference:pulsar-jms-mappings.adoc[].
* **`context.createConsumer(queue).setMessageListener(new MessageListener() {...})`**: Creates a {product} consumer context using the `createConsumer` method.
Then, `public void onMessage(Message message) {...}` initializes an `onMessage` callback to consume the messages as they arrive.
For more information about consumers, see xref:reference:pulsar-jms-mappings.adoc[].
* **`for (int i = 0; i < 10; i++) {...}`**: Sends 10 messages to the queue using the `createProducer` method.
* **`Thread.sleep(10000);`**: Sleeps for 10 seconds to allow time for all messages to be consumed before closing the connection.

. Compile the sample application:
+
[source,bash]
----
mvn clean install
----
+
The first time you compile the JAR file, Maven downloads all required dependencies.
Subsequent runs are faster.

. Run the sample application:
+
[source,bash]
----
java -jar target/StarlightForJMSClient-1.0-SNAPSHOT-jar-with-dependencies.jar
----

. Make sure the result shows that messages were sent and received.
+
It can be easy to miss message `0` in the output because it is the first line of output, and it is followed by many status lines before the rest of the messages.
+
Additionally, messages are consumed asynchronously, so the messages might not be sent and received sequentially.
+
[source,bash]
----
Sending: Hello world! 0

... TRUNCATED ...

Sending: Hello world! 1
Sending: Hello world! 2
Received: Hello world! 0
Received: Hello world! 1
Sending: Hello world! 3
Received: Hello world! 2
Sending: Hello world! 4
Received: Hello world! 3
Sending: Hello world! 5
Sending: Hello world! 6
Received: Hello world! 4
Received: Hello world! 5
Sending: Hello world! 7
Received: Hello world! 6
Sending: Hello world! 8
Received: Hello world! 7
Sending: Hello world! 9
Received: Hello world! 8
Received: Hello world! 9
[pulsar-client-io-5-1] INFO org.apache.pulsar.client.impl.ConsumerImpl - [persistent://public/default/example-topic] [jms-queue] Closed consumer
[pulsar-client-io-5-1] INFO org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/default/example-topic] [standalone-0-0] Closed Producer
[main] INFO org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: http://localhost:8080
[pulsar-client-io-5-1] INFO org.apache.pulsar.client.impl.ClientCnx - [id: 0xe43071e3, L:/127.0.0.1:65236 ! R:localhost/127.0.0.1:6650] Disconnected
----

. Use the {pulsar-short} Admin CLI or the {luna-streaming} {pulsar-short} Admin Console to inspect your tenant's activity, and verify that messages were published and consumed on the specified topic.
--

Self-managed::
+
--
include::ROOT:partial$jms-quickstart-create-project.adoc[]

. In the `example` directory, create an `App.java` file, and then paste the following code into the file:
+
./src/main/java/org/example/App.java
[source,java]
----
package example;

import com.datastax.oss.pulsar.jms.PulsarConnectionFactory;
import javax.jms.JMSContext;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.Queue;
import java.util.HashMap;
import java.util.Map;

public class App {
  public static void main(String ... args) throws Exception {

    String topic = "persistent://public/default/example-topic";

    Map<String, Object> properties = new HashMap<>();

    try (PulsarConnectionFactory factory = new PulsarConnectionFactory(properties); ){
      JMSContext context = factory.createContext();
      Queue queue = context.createQueue(topic);

      // Listen for messages...
      context.createConsumer(queue).setMessageListener(new MessageListener() {
        @Override
        public void onMessage(Message message) {
          try {
              System.out.println("Received: " + message.getBody(String.class));
            } catch (Exception err) {
              err.printStackTrace();
            }
          }
      });

      for (int i = 0; i < 10; i++) {
        String message = "Hello world! " + i;
        System.out.println("Sending: "+message);
        context.createProducer().send(queue, message);
      }

      Thread.sleep(10000);
    }
  }
}
----
+
Note the following elements of the `App.java` program:
+
* **`persistent://public/default/example-topic`**: The topic URI that the client uses to publish and consume messages.
This quickstart uses the default tenant and namespace with a topic named `example-topic`.
The tenant and namespace must already exist.
If the specified topic doesn't exist in the namespace, {product} creates the topic automatically.
* **`Map<String, Object> properties = new HashMap<>();`**: Creates an empty xref:reference:pulsar-jms-reference.adoc[{product} configuration properties] hashmap.
You must override `webServiceUrl` if your {pulsar-short} cluster's admin endpoint isn't accessible on `\http://localhost:8080`.
For remote clusters, additional properties are required, such as the Broker Service URL and authentication credentials.
* **`Queue queue = context.createQueue(topic);`**: Creates a {product} queue.
For more information about queues and topics, see xref:reference:pulsar-jms-mappings.adoc[].
* **`context.createConsumer(queue).setMessageListener(new MessageListener() {...})`**: Creates a {product} consumer context using the `createConsumer` method.
Then, `public void onMessage(Message message) {...}` initializes an `onMessage` callback to consume the messages as they arrive.
For more information about consumers, see xref:reference:pulsar-jms-mappings.adoc[].
* **`for (int i = 0; i < 10; i++) {...}`**: Sends 10 messages to the queue using the `createProducer` method.
* **`Thread.sleep(10000);`**: Sleeps for 10 seconds to allow time for all messages to be consumed before closing the connection.

. Compile the sample application:
+
[source,bash]
----
mvn clean install
----
+
The first time you compile the JAR file, Maven downloads all required dependencies.
Subsequent runs are faster.

. Run the sample application:
+
[source,bash]
----
java -jar target/StarlightForJMSClient-1.0-SNAPSHOT-jar-with-dependencies.jar
----

. Make sure the result shows that messages were sent and received.
+
It can be easy to miss message `0` in the output because it is the first line of output, and it is followed by many status lines before the rest of the messages.
+
Additionally, messages are consumed asynchronously, so the messages might not be sent and received sequentially.
+
[source,bash]
----
Sending: Hello world! 0

... TRUNCATED ...

Sending: Hello world! 1
Sending: Hello world! 2
Received: Hello world! 0
Received: Hello world! 1
Sending: Hello world! 3
Received: Hello world! 2
Sending: Hello world! 4
Received: Hello world! 3
Sending: Hello world! 5
Sending: Hello world! 6
Received: Hello world! 4
Received: Hello world! 5
Sending: Hello world! 7
Received: Hello world! 6
Sending: Hello world! 8
Received: Hello world! 7
Sending: Hello world! 9
Received: Hello world! 8
Received: Hello world! 9
[pulsar-client-io-5-1] INFO org.apache.pulsar.client.impl.ConsumerImpl - [persistent://public/default/example-topic] [jms-queue] Closed consumer
[pulsar-client-io-5-1] INFO org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/default/example-topic] [standalone-0-0] Closed Producer
[main] INFO org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: http://localhost:8080
[pulsar-client-io-5-1] INFO org.apache.pulsar.client.impl.ClientCnx - [id: 0xe43071e3, L:/127.0.0.1:65236 ! R:localhost/127.0.0.1:6650] Disconnected
----

. Use the {pulsar-short} Admin CLI to inspect your tenant's activity, and verify that messages were published and consumed on the specified topic.

. If you used a {pulsar-short} Docker instance for this quickstart, stop and remove the Docker container when you are done testing the quickstart program:
+
.. In the terminal where you started the {pulsar-short} Docker instance, press kbd:[Ctrl]+kbd:[C] to stop the container.
.. Get a list of all Docker containers, and then note the container ID for the `apachepulsar` container:
+
[source,bash]
----
docker ps --all
----
+
.Result
[%collapsible]
====
In the following example result, the container ID is `5116f0d16eb3`:

[source,bash]
----
CONTAINER ID   IMAGE                        COMMAND                  CREATED       STATUS                       PORTS                  NAMES
5116f0d16eb3   apachepulsar/pulsar:latest   "/pulsar/bin/pulsar …"   2 hours ago   Exited (130) 2 minutes ago                          pulsar-jms-runner
7ed5fc6c9776   cassandra:latest             "docker-entrypoint.s…"   7 days ago    Exited (143) 7 days ago                             my_cass
----
====
.. Delete the container by its container ID:
+
[source,bash,subs="+quotes"]
----
docker rm **CONTAINER_ID**
----
--
======

== Next steps

* xref:starlight-for-jms:examples:pulsar-jms-implementation.adoc[]
* xref:starlight-for-jms:reference:pulsar-jms-mappings.adoc[]
* xref:starlight-for-jms:reference:pulsar-jms-reference.adoc[]
* xref:ROOT:pulsar-jms-faq.adoc[]