= Install {product}
:navtitle: Installation

[TIP]
====
For a guided tutorial on installing and using {product}, see the xref:jms-migration:pulsar-jms-quickstart-sa.adoc[quickstart].
====

Install {jms_repo}[{product}] by adding the dependency to your Java project.
For example:

.pom.xml
[source,xml,subs="+quotes"]
----
<dependency>
   <groupId>com.datastax.oss</groupId>
   <artifactId>pulsar-jms-all</artifactId>
   <version>**VERSION**</version>
</dependency>
----

There are two {product} packages available:

* **`pulsar-jms`**: This package contains only {product} code.
It transitively imports the {pulsar-short} client and the Jakarta JMS 2.0 specifications JAR.
* **`pulsar-jms-all`**: This is the fat JAR that includes {product} and all required dependencies, including the {pulsar-short} client and the Jakarta JMS 2.0 specifications.

{company} recommends the latest version whenever possible.
However, certain features and compatibility issues require a specific version:

{astra-stream}::
The {pulsar-short} version is managed by {astra}.
Typically, the latest {product} version is compatible with the {pulsar-short} version used by {astra-stream}.

{luna-streaming}::
+
[TIP]
====
{luna-streaming} was formerly DataStax Luna Streaming.
====
+
* To use Transactions with {luna-streaming} 2.8.x, you must use {product} version 1.x.
* To use Transactions with {luna-streaming} 2.10.x or later, you must use {product} version 2.x or later.
* To use server-side filtering, you must use {luna-streaming} 2.10.0 or later _and_ {product} 2.x or later.

Self-managed {pulsar-short}::
* To use Transactions with self-managed {pulsar-short} 2.8.x, you must use {product} version 1.x.
* To use Transactions with self-managed {pulsar-short} 2.9.x, 2.10.x, or later, you must use {product} version 2.x or later.
* To use server-side filtering with self-managed {pulsar-short}, you must use {pulsar-short} 2.10.1 or later and {product} 2.x or later.