= Map {pulsar-short} concepts to JMS specifications

JMS specifications are built upon the concepts of _topics_ and _queues_, but {pulsar-reg} has only a general concept of topics that can model both of those domains.

In {pulsar-short} there is no concept of a queue.
Therefore, {product} treats {pulsar-short} topics as queues when queue-related JMS API are in use.
There is no strict cluster-wide verification that you are accessing a JMS Queue using the Topic API or vice versa.

In JMS, a topic is written by many _producers_ and read by many _consumers_ that share one or many _subscriptions_.
Subscriptions can be _durable_ or _non-durable_, which determines whether the client position is retained on restart.
Subscriptions can also be _shared_ or _non-shared_, which determines whether the same message can be received and processed by multiple consumers.

[#jms-pulsar-consumers]
== Mapping of JMS consumers/subscriptions to Apache consumers for topics

[cols="a,a"]
|===
| JMS Concept | {pulsar-short} Concept

| Topic
| Persistent topic

| Consumer
| Exclusive non-durable subscription with random name (`UUID`)

| DurableConsumer
| Exclusive durable subscription with the given name and `clientId`

| SharedConsumer
| Shared non-durable subscription with the given name and `clientId`

| SharedDurableConsumer
| Shared durable subscription with the given name and `clientId`

| DurableSubscriber
| Exclusive durable subscription with the given name and `clientId`
|===

TIP: As of {pulsar-short} version 2.7.x, delayed messages don't work with exclusive subscriptions. You can, however, force the usage of shared non-durable subscriptions for simple consumers by setting `jms.useExclusiveSubscriptionsForSimpleConsumers=false`.

For `SharedConsumer` and `SharedDurableConsumer`, set `jms.topicSharedSubscriptionType` to `Key_Shared` to use the `Key_Shared` subscription type.

In JMS a *Queue* is written by many *Producers* but only one *Consumer* eventually processes each message.

In order to emulate that behavior, the first time you create a consumer over a queue, {product} creates a durable subscription named `jms-queue` at the beginning (initial position = Earliest) of the {pulsar-short} topic.

Every access to the queue passes through the shared subscription and guarantees that only one consumer receives and processes each message.

[#subscriptions]
== Mapping of JMS consumer/subscriptions to Apache consumers for queues

[cols="a,a"]
|===
| JMS Concept | {pulsar-short} Concept

| Queue
| Persistent topic

| Consumer
| Shared durable subscription with name `jms-queue`

| QueueBrowser
| {pulsar-short} Reader for the topic, beginning from the next message on `jms-queue` subscription
|===

You can change the name of the shared subscription using the `jms.queueSubscriptionName` configuration parameter, but you must ensure that you change it on every client.

In order to implement `QueueBrowser`, {product} uses the {pulsar-short} Reader API, starting from the next message available on the `jms-queue` subscription. In order to peek at the next message {product} uses the {pulsar-short} Admin API `peekMessages`.

In certain cases, the `peekMessages` API can return the last consumed message of the subscription, so the `QueueBrowser` can return inaccurate results.

[#jms-queue]
=== Override `jms-queue`

By default, the subscription created by a JMS queue is named `jms-queue`, which can be overriden with `jms.queueSubscriptionName` in the `PulsarConnectionFactory` constructor.

You can instead set the subscription name at queue creation:

[source,java]
----
try (PulsarConnectionFactory factory = new PulsarConnectionFactory(properties); ){
    Queue queue = session.createQueue("pulsarQueue:subscriptionName");
}
----

In the above example, the subscription will be `subscriptionName`, and the queue will be backed by the `public/default/pulsarQueue` {pulsar-short} topic.

You can override the default `public/default` namespace with `jms.systemNamespace` in the `PulsarConnectionFactory` constructor:

[source,java]
----
Map<String, Object> configuration = new HashMap<>();
    configuration.put("jms.systemNamespace", "<my-tenant>/<my-namespace>");

ConnectionFactory factory = new PulsarConnectionFactory(configuration);
    ...
    factory.close();
----

A fully-qualified namespace works similarly, but the topic destination points to a persistent topic URL:

[source,java]
----
Queue queue = session.createQueue("persistent://tenant/namespace/pulsarQueue:subscriptionName")
----

In the above example, the subscription will be `subscriptionName`, and the queue will be backed by the `persistent://tenant/namespace/pulsarQueue` {pulsar-short} topic.

=== Disable automatic subscription creation

By default, the `jms.precreateQueueSubscription` configuration flag is set to `true`, and the JMS client pre-creates the `jms-queue` subscription (see xref:pulsar-jms-mappings.adoc#jms-queue[Overriding jms-queue] above).

To disable automatic subscription creation in the JMS client, set the `jms.precreateQueueSubscription` parameter to `false`, as below:

[source,java]
----
Map<String, Object> properties = new HashMap<>();
    properties.put("jms.precreateQueueSubscription", "false");
----

To disable automatic subscription creation on the {pulsar-short} broker, set the `allowAutoSubscriptionCreation` parameter to `false`, as below:

[source,java]
----
public static void before() throws Exception {
    cluster =
        new PulsarCluster(
            tempDir,
            config -> {
              config.setAllowAutoSubscriptionCreation(false);
            });
    cluster.start();
}
----

Or modify the {pulsar-short} broker's `broker.conf` file:

[source,plaintext]
----
allowAutoSubscriptionCreation=false
----

If both `allowAutoSubscriptionCreation` and `jms.precreateQueueSubscription` are set to `false`, automatic subscription creation is completely disabled.

[#consumer-mappings]
== Mapping of JMS consumer modes to {pulsar-short} concepts

There are five consumer mode session objects in JMS. This section describes how they map to {pulsar-short} concepts.

[#auto-ack]
=== Session.AUTO_ACKNOWLEDGE

This mode maps to the {pulsar-short} `acknowledgeMessage` API.

By default, acknowledgements in {pulsar-short} are asynchronous and best effort, enabling duplicates to always be displayed on the Consumer.

In the example below, we create a consumer on `mytopic` with `Session.AUTO_ACKNOWLEDGE`, send 100 `foo` messages, and auto-acknowledge them.

[source,java]
----
import com.datastax.oss.pulsar.jms.PulsarConnectionFactory;

import javax.jms.Connection;
import javax.jms.JMSContext;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.MessageProducer;
import javax.jms.Queue;
import javax.jms.Session;
import javax.jms.TextMessage;
import java.util.HashMap;
import java.util.Map;

public class JMSExample {

    public static void main(String ... args) throws Exception {

        // start pulsar standalone on localhost

        // the topic is autocreated, no additional setup is needed
        String topic = "persistent://public/default/mytopic";

        Map<String, Object> properties = new HashMap<>();

        try (PulsarConnectionFactory factory = new PulsarConnectionFactory(properties); ){
            try (Connection connection = factory.createConnection()) {
                try (Session session = connection.createSession(Session.AUTO_ACKNOWLEDGE)) {
                    Queue queue = session.createQueue(topic);

                    session.createConsumer(queue).setMessageListener(new MessageListener() {
                        @Override
                        public void onMessage(Message message) {
                            try {
                                System.out.println("received " + message.getBody(String.class));

                            } catch (Exception err) {
                                err.printStackTrace();
                            }
                        }
                    });

                    try (MessageProducer producer = session.createProducer(queue)) {
                        for (int i = 0; i < 100; i++) {
                            String message = "foo" + i;
                            System.out.println("sending " + message);
                            TextMessage textMessage = session.createTextMessage(message);
                            producer.send(textMessage);
                        }
                    }

                    // waiting 10 seconds, in order to see all messages consumed
                    Thread.sleep(10000);
                }
            }
        }
    }
}
----

[#dups-ok]
=== Session.DUPS_OK_ACKNOWLEDGE

This mode maps to `Consumer.acknowledgeAsync()` without waiting for the `CompleteableFuture` returned by the method to complete.

{product} logs an error in case there is a problem, but the application continues running and isn't aware of the failure.

In the example below, we create a consumer on `mytopic` with `Session.DUPS_OK_ACKNOWLEDGE`, send 100 `foo` messages, and acknowledge them without waiting for the `CompleteableFuture` method to complete.

[source,java]
----
import com.datastax.oss.pulsar.jms.PulsarConnectionFactory;

import javax.jms.Connection;
import javax.jms.JMSContext;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.MessageProducer;
import javax.jms.Queue;
import javax.jms.Session;
import javax.jms.TextMessage;
import java.util.HashMap;
import java.util.Map;

public class JMSExample {

    public static void main(String ... args) throws Exception {

        // start pulsar standalone on localhost

        // the topic is autocreated, no additional setup is needed
        String topic = "persistent://public/default/mytopic";

        Map<String, Object> properties = new HashMap<>();

        try (PulsarConnectionFactory factory = new PulsarConnectionFactory(properties); ){
            try (Connection connection = factory.createConnection()) {
                try (Session session = connection.createSession(Session.DUPS_OK_ACKNOWLEDGE)) {
                    Queue queue = session.createQueue(topic);

                    session.createConsumer(queue).setMessageListener(new MessageListener() {
                        @Override
                        public void onMessage(Message message) {
                            try {
                                System.out.println("received " + message.getBody(String.class));

                            } catch (Exception err) {
                                err.printStackTrace();
                            }
                        }
                    });

                    try (MessageProducer producer = session.createProducer(queue)) {
                        for (int i = 0; i < 100; i++) {
                            String message = "foo" + i;
                            System.out.println("sending " + message);
                            TextMessage textMessage = session.createTextMessage(message);
                            producer.send(textMessage);
                        }
                    }

                    // waiting 10 seconds, in order to see all messages consumed
                    Thread.sleep(10000);
                }
            }
        }
    }
}
----

[#client-ack]
=== Session.CLIENT_ACKNOWLEDGE

In this mode the JMS client works like `AUTO_ACKNOWLEDGE`, automatically acknowledging all messages received before the message inside the same session. To acknowledge only the individual message, use xref:pulsar-jms-mappings.adoc#individual[PulsarJMSConstants.INDIVIDUAL_ACKNOWLEDGE].

In the example below, we create a consumer on `mytopic` with `Session.CLIENT_ACKNOWLEDGE`, send 100 `foo` messages, and acknowledge them by calling `Message.acknowledge()`in the `onMessage` method.

This message and all previous messages in the session are acknowledged.

[source,java]
----
import com.datastax.oss.pulsar.jms.PulsarConnectionFactory;

import javax.jms.Connection;
import javax.jms.JMSContext;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.MessageProducer;
import javax.jms.Queue;
import javax.jms.Session;
import javax.jms.TextMessage;
import java.util.HashMap;
import java.util.Map;

public class JMSExample {

    public static void main(String ... args) throws Exception {

        // start pulsar standalone on localhost

        // the topic is autocreated, no additional setup is needed
        String topic = "persistent://public/default/mytopic";

        Map<String, Object> properties = new HashMap<>();

        try (PulsarConnectionFactory factory = new PulsarConnectionFactory(properties); ){
            try (Connection connection = factory.createConnection()) {
                try (Session session = connection.createSession(Session.CLIENT_ACKNOWLEDGE)) {
                    Queue queue = session.createQueue(topic);

                    session.createConsumer(queue).setMessageListener(new MessageListener() {
                        @Override
                        public void onMessage(Message message) {
                            try {
                                System.out.println("received " + message.getBody(String.class));
                                message.acknowledge();
                            } catch (Exception err) {
                                err.printStackTrace();
                            }
                        }
                    });

                    try (MessageProducer producer = session.createProducer(queue)) {
                        for (int i = 0; i < 100; i++) {
                            String message = "foo" + i;
                            System.out.println("sending " + message);
                            TextMessage textMessage = session.createTextMessage(message);
                            producer.send(textMessage);
                        }
                    }

                    // waiting 10 seconds, in order to see all messages consumed
                    Thread.sleep(10000);
                }
            }
        }
    }
}
----

[#individual]
=== PulsarJMSConstants.INDIVIDUAL_ACKNOWLEDGE

In this mode the JMS client works like `CLIENT_ACKNOWLEDGE`, but when you call `Message.acknowledge()`, only the single message you called for is acknowledged.

[IMPORTANT]
====
This is a proprietary extension that isn't present in the standard JMS 2.0 specifications.
====

In the example below, we create a consumer on `mytopic` with `PulsarJMSConstants.INDIVIDUAL_ACKNOWLEDGE`, send 100 `foo` messages, and acknowledge them by calling `Message.acknowledge()`in the `onMessage` method.

Only the individual message is acknowledged.

[source,java]
----
import com.datastax.oss.pulsar.jms.PulsarConnectionFactory;

import javax.jms.Connection;
import javax.jms.JMSContext;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.MessageProducer;
import javax.jms.Queue;
import javax.jms.Session;
import javax.jms.TextMessage;
import java.util.HashMap;
import java.util.Map;

public class JMSExample {

    public static void main(String ... args) throws Exception {

        // start pulsar standalone on localhost

        // the topic is autocreated, no additional setup is needed
        String topic = "persistent://public/default/mytopic";

        Map<String, Object> properties = new HashMap<>();

        try (PulsarConnectionFactory factory = new PulsarConnectionFactory(properties); ){
            try (Connection connection = factory.createConnection()) {
                try (Session session = connection.createSession(PulsarJMSConstants.INDIVIDUAL_ACKNOWLEDGE)) {
                    Queue queue = session.createQueue(topic);

                    session.createConsumer(queue).setMessageListener(new MessageListener() {
                        @Override
                        public void onMessage(Message message) {
                            try {
                                System.out.println("received " + message.getBody(String.class));
                                message.acknowledge();
                            } catch (Exception err) {
                                err.printStackTrace();
                            }
                        }
                    });

                    try (MessageProducer producer = session.createProducer(queue)) {
                        for (int i = 0; i < 100; i++) {
                            String message = "foo" + i;
                            System.out.println("sending " + message);
                            TextMessage textMessage = session.createTextMessage(message);
                            producer.send(textMessage);
                        }
                    }

                    // waiting 10 seconds, in order to see all messages consumed
                    Thread.sleep(10000);
                }
            }
        }
    }
}
----

[#transacted]
=== Session.SESSION_TRANSACTED

The acknowledgement is bound to the Transaction, and the acknowledgement is sent to the broker only during `Transaction.commit()`.

If you're porting a JMS application that is using `SESSION_TRANSACTED` but don't need to perform the transaction's operations, enable `jms.emulateTransactions`.
See xref:examples:pulsar-jms-implementation.adoc[Transaction Emulation].

[#interoperability]
== Interoperability between {product} and other {pulsar-short} clients

{product} doesn't deal with schema, and it treats every message as a raw array of bytes, interpreting the content of the message according to the JMS API that is used, and to a special `JMSPulsarMessageType` property.

JMS specs require that, on the consumer side, you receive a message of the *same type* sent by the producer:

* `TextMessage`
* `BytesMessage`
* `StreamMessage`
* `MapMessage`
* `ObjectMessage`

When the JMS consumer receives a message that hasn't been produced by {product} itself and lacks the `JMSPulsarMessageType` property, it converts the message to a `BytesMessage`.

=== {pulsar-short} message keys and JMSXGroupID

The special `JMSXGroupID` property is defined in the JMS specs as a way to group messages and enable routing to the same destination.

{product} maps that property to the message key in {pulsar-short}, ensuring that `JMSXGroupID` is used as the routing key.

This is the same behavior implemented in https://activemq.apache.org/message-groups[{activemq-reg}].

== See also

* xref:examples:pulsar-jms-implementation.adoc[]
* xref:pulsar-jms-reference.adoc[]