= {product} configuration reference
:navtitle: Configuration reference

A complete configuration reference for {product}.

== Set configuration options

Configuration information is passed to the `PulsarConnectionFactory` constructor:

[source,java]
----
Map<String, Object> configuration = new HashMap<>();
configuration.put("...","...");
ConnectionFactory factory = new PulsarConnectionFactory(configuration);
...
factory.close();
----

Configuration information can also be passed as a JSON encoded string:

[source,java]
----
String configuration = "{.....}";
ConnectionFactory factory = new PulsarConnectionFactory();
factory.setJsonConfiguration(configuration);
...
factory.close();
----

Configuration information can be passed when a `JMSContext` or `Session` is created with `JMSContext.createContext` or `Session.createSession`.

Create a `PulsarConnectionFactory` with `initialContext` for configuration:

[source,java]
----
Map<String, Object> configuration = new HashMap<>();
Map<String, Object> consumerConfig = new HashMap<>();
configuration.put("consumerConfig", consumerConfig);
PulsarConnectionFactory factory = new PulsarConnectionFactory(configuration);
PulsarJMSContext initialContext = (PulsarJMSContext) factory.createContext();
----

The initial configuration in `initialContext` is overridden by the subsequent `JMSContext` configuration `withCustomConfiguration`:

[source,java]
----
Map<String, Object> perContextConfiguration new HashMap<>();
Map<String, Object> perContextConsumerConfig = new HashMap<>();
perContextConsumerConfig.put("consumerConfig", perContextConsumerConfig);
JMSContext withCustomConfiguration = initialContext.createContext(mode, perContextConfiguration);
----

Or override the initial configuration in `initialContext` with the `JMSContext` configuration `withCustomConfiguration` in a Session object:

[source,java]
----
Session.createSession(int mode, Map<String, Object> withCustomConfiguration)
----

[IMPORTANT]
====
The configuration related to `consumerConfig` is the only configuration that can be overridden with `createContext`.
Other entries are ignored.
====

== Configuration options

[cols="3,1,1,2,4"]
|===
| Configuration Entry | Required | Type | Default value | Notes

| `ackTimeout`
| no
| long
| Disabled
| Set timeout for unacked messages. Must be >1 second.

| `ackTimeoutMillis`
| no
| long
|
| Same as `ackTimeout`, but expressed in milliseconds

| `brokerServiceUrl`
| no
| String
| If not specified, for {pulsar-short} standalone instances running on localhost, defaults to the same value as `webServiceUrl`, \`http://localhost:8080`. Can also be specified as \`pulsar://localhost:6650` for {pulsar-short} standalone instances on localhost.
a| The URL to connect to the {pulsar-short} broker or proxy
The `brokerServiceUrl` must be specified for {astra-streaming}. Must be customized as required for {pulsar-short} standalone instances that aren't running on localhost.

| `consumerConfig`
| no
| Map<String,Object>
| Empty Map
a| Additional configuration for each {pulsar-short} Consumer.
For all valid consumer objects, see the https://pulsar.apache.org/docs/client-libraries-java/#configure-consumer[{pulsar} documentation].

| `enableTransaction`
| no
| boolean
| false
a| Enable transactions
`enableTransaction` defaults to `false` because transaction support isn't enabled by default in {pulsar-short} 2.7, and the client cannot connect to a cluster that doesn't enable transactions.

| `jms.acknowledgeRejectedMessages`
| no
| boolean
| false
a| Force acknowledgment of filtered messages on shared subscriptions
By default, filtered messages are negatively acknowledged on shared subscriptions. If this flag is `true`, they are acknowledged in order to skip them definitively.

| `jms.allowTemporaryTopicWithoutAdmin`
| no
| boolean
| false
a| Allows temporary topic/queue creation and deletion to pass without errors when `jms.usePulsarAdmin` is set to `false`.
Use the default values of `allowAutoTopicCreation=true` and `allowAutoTopicCreationType=non-partitioned` in `broker.conf` for auto-creation of temporary topics/queues.

| `jms.clientId`
| no
| String
| empty string
a| Administratively assigned `clientId` (see the JMS specs).
The default value assigned to every Connection.

| `jms.emulateTransactions`
| no
| boolean
| false
| When a `SESSION_TRANSACTED` session is created in this mode, the Session behaves like a transacted Session but it isn't transactional.
A produced message is sent immediately, and acknowledgements are sent during `session.commit()`.
See xref:examples:pulsar-jms-implementation.adoc[Transaction Emulation].

| `jms.enableClientSideEmulation`
| no
| boolean
| false
a| Enable emulated features.
Enable features that aren't supported directly by the {pulsar-short} Broker but are emulated on the client side.

| `jms.forceDeleteTemporaryDestinations`
| no
| boolean
| false
a| Force the deletion of temporary destinations.
Use the {pulsar-short} API to force the deletion even if the temporary destination has active subscriptions.

| `jms.precreateQueueSubscription`
| no
| boolean
| true
a| When set to `false`, the JMS client doesn't pre-create the subscription `jms-queue`.
Set `allowAutoSubscriptionCreation=false` in `broker.conf` to disable subscription auto-creation on the broker.

| `jms.queueSubscriptionName`
| no
| String
| jms-queue
a| Name of the system subscription used to emulate JMS Queues

| `jms.systemNamespace`
| no
| String
| public/default
a| Default {pulsar-short} namespace in which temporary destinations and destinations without an explicit namespace are created

| `jms.topicSharedSubscriptionType`
| no
| String
| Shared
| Type of subscription for Shared consumers: `Shared`, `Key_shared`, or `Failover`.
Type of subscription is defined when a consumer connects to the subscription.

| `jms.transactionsStickyPartitions`
| no
| boolean
| false
a| Force all messages sent in scope of a transaction to go to the same partition.


| `jms.useCredentialsFromCreateConnection`
| no
| boolean
| false
a| Makes `authParams` the username/password pair passed to `ConnectionFactory.createConnection(username, password)` and `ConnectionFactory.createContext(username, password, mode)`

| `jms.useExclusiveSubscriptionsForSimpleConsumers`
| no
| boolean
| true
a| Use an Exclusive subscription for Topic consumers.
Set this to `false` to enable Delayed Messages.

| `jms.usePulsarAdmin`
| no
| boolean
| true
a| Allow the client to use the {pulsar-short} Admin API.
Set this to `false` if your client cannot access the Admin HTTP API.

| `jms.useServerSideFiltering`
| no
| boolean
| false
a| Offloads message filtering to the Broker nodes. See xref:examples:pulsar-jms-server-side-filters.adoc[Server Side Filters].

| `jms.waitForServerStartupTimeout`
| no
| number
| 60000
a| Grace period in ms to wait for the {pulsar-short} broker to be available.
Used to wait for Queue subscriptions to be ready.

| `negativeAckRedeliveryBackoff`
| no
| `RedeliveryBackoff`
| MultiplierRedeliveryBackoff
a| Interface for custom message is `ackTimeout` policy. You can specify `RedeliveryBackoff` for a consumer.

| `producerConfig`
| no
| Map<String,Object>
| Empty Map
a| Additional configuration for each {pulsar-short} Producer

| `webServiceUrl`
| yes
| String
| \`http://localhost:8080` (default)
a| Main {pulsar-short} HTTP endpoint.
Must be customized as required for {pulsar-short} standalone instances that aren't running on localhost.

|===

All other options are passed as configurations to the {pulsar-short} Client and the {pulsar-short} Admin client, allowing you to configure additional {pulsar-short} features, including https://pulsar.apache.org/docs/en/security-tls-keystore/#configuring-clients[security].

TIP: Please check https://pulsar.apache.org/docs/en/standalone/[{pulsar} documentation] for a complete list of configuration options.

== See also

* xref:pulsar-jms-mappings.adoc[]
* xref:examples:pulsar-jms-implementation.adoc[]